default: &default
  adapter: postgresql
  encoding: unicode
  username: theophile
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: image_gallery_api_development
  username: theophile
test:
  <<: *default
  database: image_gallery_api_test
  username: theophile
production:
  <<: *default
  database: image_gallery_api_production
  username: image_gallery_api
