default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USER_NAME'] %>
  password: <%= ENV['PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: image_gallery_api_development
  username: <%= ENV['USER_NAME'] %>
  password: <%= ENV['PASSWORD'] %>
test:
  <<: *default
  database: image_gallery_api_test
  username: <%= ENV['USER_NAME'] %>
  password: <%= ENV['PASSWORD'] %>
production:
  <<: *default
  database: image_gallery_api_production
  username: image_gallery_api
